version: '3'

services:
  api:
    build: ./api
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "80:3000"
    volumes:
      - ./api:/usr/api/
      - node_modules:/usr/api/node_modules
    depends_on:
      - mongo
    command: nodemon -L app.js

  mongo:
    image: mongo
    container_name: mongo
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
    volumes:
      - dbdata:/data/db

  #DELETE IN PRODUCTION
  mongo-ui:
    image: mongo-express
    ports:
      - 8081:8081
    env_file: .env
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=$MONGO_PORT
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASSWORD
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=$MONGO_USERNAME
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=$MONGO_PASSWORD
      - ME_CONFIG_BASICAUTH_USERNAME=$MONGO_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD=$MONGO_PASSWORD

volumes:
  dbdata:
  node_modules:
